"""Render one Open Graph card per view, so a shared link previews as the view it actually is.

`19_pages.py` and `20_landing.py` both used to point `og:image` at
`opengraph.githubassets.com/1/<repo>`, which is the same generic repository card on all 157 URLs this
site publishes. The whole pitch is that "the best Claude Code observability tool" is a *link*; in
Slack, Discord, X and iMessage that link looked identical to a link to the repository's front page --
which is the one surface where the crossing this site exists to show does not exist at all.

That card is now the fallback on both stages rather than the default, and it is a build-time fallback:
each page ships exactly one `og:image`, chosen by whether the file this stage writes is on disk.

  docs/og/root.png             1, the unfiltered view -- the bare site link
  docs/og/topic-<slug>.png     14, one per topic
  docs/og/target-<slug>.png    12, one per target
  docs/og/cards.json           what each card says, and the signature that decides re-rendering

  python scripts/23_og.py
  python scripts/23_og.py --out build/og    render somewhere other than what Pages serves

After `20_landing.py`, and it reads the dataset through that stage's own `plan()` rather than
regrouping 1,294 rows a second time: a card and the page it belongs to cannot then disagree about a
count or about which three projects are the biggest. Nothing else is imported from it, so the two
stages stay independently runnable.

Seven decisions, in the order they cost the most.

The root page is a view like any other -- the one with no filter -- and it gets its card from the same
two functions. It is the only URL here anybody actually pastes into Slack, and until `root.png` existed
it was the only URL still previewing as the generic repository card that this whole stage exists to
replace: the deep links nobody shares had a real card and the front door did not. What it carries is
the one thing `opengraph.githubassets.com` cannot, because that image is rendered from a repository name
and a description: the size of the dataset. Project count, source lists, topics and the snapshot date,
which are the same four numbers `docs/index.html` prints in its own header, out of the same
`data.json`. `cards()` emits it ahead of the 26 and `card_html` draws it unchanged; the only
generalisation either needed was to stop hardcoding the host line's suffix, so that the root card can
carry a date there and a facet card can carry nothing, which is what it carried before.

27 cards, not 157. The 130 crossings reuse their topic's card. What a per-crossing image would add
over its topic's is that cell's own count and top three -- and `20_landing.py` already writes both
into the crossing's `<title>` and `<meta name=description>`, which is the text every one of those
scrapers renders beside the image. The bill for the duplicate is six times the bytes in a format that
cannot delta-compress: every generated byte is committed, because Pages serves this branch's `docs/`
folder. So the card says "every harness" or "every topic" out loud, and a topic card sitting beside a
crossing page's own "12 projects that plug into Claude Code" cannot be read as a claim about that
cell. To reverse the decision, drop the `bool(p.cat) == bool(p.tgt)` skip in `cards()` and give the
crossings a `topic-<a>--target-<b>.png`; nothing else in this stage counts on there being 27.

Nothing that moves daily goes on a facet card. These pages lead with combined stars and a snapshot date
and neither is on one of the 26, because a PNG whose pixels moved is a whole new object in the pack for
ever -- there is no such thing as a small edit to one. The count is floored to a multiple of ten and
suffixed `+` for the same reason: "470+ projects" stays true about ten times longer than "479 projects"
does, and a social card is not where anybody reads a precise number. The three names are the top three
by stars, printed in alphabetical order under a label rather than numbered, because the *set* of the
three biggest projects in a facet holds for months while the order of the second and third flips
whenever they trade a few hundred stars -- and a numbered list would turn every one of those flips into
a rewrite of the whole file.

`root.png` is the one exception, and it is a knowing one: it carries `data.json`'s snapshot date, so it
is re-rendered whenever the dataset is refetched. That is up to 52 rewrites of one ~25 KB file a year
against zero, which is the price of the card answering "is this current?" for the one URL anybody
shares -- an atlas whose whole claim is that it is rebuilt daily cannot make that claim on a card that
is deliberately undated. Two things follow, and both are real. `weekly.yml` runs this stage and
`daily.yml` does not, so between weekly runs the date on the card is behind the date the page prints:
the card is never wrong about a snapshot that existed, but it can be up to six days older than the
page's. And the floored count moves the same way -- "1,290+" is true the day it is rendered and stays
true while the index grows, but a week of *net removals* below 1,290 would leave it overstating until
the next weekly run. Drop `"note"` from the root record in `cards()` to take the date back off and get
the facet cards' churn profile; nothing else depends on it.

A card is re-rendered only when what it says or how it looks changes. `docs/og/cards.json` holds the
exact strings that went onto each card plus a signature over them, over `PALETTE` and over `TEMPLATE`,
so an unchanged facet costs no browser launch and, more to the point, no bytes. That is what stops a
Chromium update on the runner from rewriting the entire set: `weekly.yml` does `pip install --upgrade
playwright` and then `playwright install chromium`, so the rasterizer moves every few weeks, and text
rendered a pixel differently is 27 new objects. Committed rather than left in `cache/`, which is
gitignored and restored best-effort -- a cache miss there would be indistinguishable from 27 changed
cards and would cost the history ~540 KB to find that out. `PALETTE` is in the signature rather than
trusted to a human because the colours are the half of "how it looks" that a re-theme actually touches,
and a cache key that does not cover its own input ships a stale artefact and reports success -- see
`signature()`. `TEMPLATE` stays for the half the hash cannot see: bump it to force the set through after
a layout change, and only after one, because a bump that changes no pixels still costs that ~540 KB. The
optional `"note"` key is there for exactly that reason: a facet record does not carry it, so a facet
signature did not move when the root card was added, so this stage rendered one file rather than 27.

A missing browser is not an error. Same contract as `15_shots_all.py` and `06_web_shots.py`: one
subprocess per image, `chrome.find()` may return None, and None degrades. It degrades better here
than there, because these cards are committed -- so "no Chromium" means the cards already on disk are
left exactly as they are, which is also what a card whose content did not change gets. The only state
this cannot serve is a view that has never been rendered, and the page stages handle that one by
listing `docs/og/` and falling back to the repository card for any page whose file is not there --
`20_landing.py` for the 156 facet pages, `19_pages.py` for the root. Note which way round the ordering
runs: both of those stages emit their `og:image` *before* this one writes the images, so a card's first
ever render lands one build after the tag that would point at it. Committing the card is what closes
that gap; a card generated and not committed leaves the page on the repository fallback for ever.

Chrome's PNG is re-encoded as an indexed one, with `zlib` and nothing else. A card is flat fills and
antialiased text, so 8-bit RGB spends three bytes on a palette of about 1,900 colours of which 256
cover 99.2% of the pixels: indexing costs ~24 KB where Chrome writes ~60 KB, and the 2.5x applies to
every rewrite for the life of the repository. Lossless when a render has 256 colours or fewer, and
nearest-neighbour among the 256 most frequent otherwise, which on this design is invisible -- every
colour in the image is a point on a blend between one of six inks and one of three backgrounds, so
the nearest palette entry is a neighbour on the same ramp. Anything this cannot parse as an 8-bit
non-interlaced RGB or RGBA PNG is written through unchanged: a smaller card is worth having and a
corrupt one is not.

Dark only. The site ships a light theme and this does not, because a scraper never tells us which one
the reader has and dark is the designed mode -- the mode whose eight neutrals and two accents were
measured. A light card would be a second 27 files that nobody can request.
"""
from __future__ import annotations

import hashlib
import importlib.util
import json
import struct
import subprocess
import sys
import tempfile
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HERE = Path(__file__).resolve().parent
OUT = ROOT / "docs" / "og"

sys.path.insert(0, str(HERE))
import chrome  # noqa: E402

# The dynamic load `20_landing.py` and `19b_refresh.py` both use, for the same reason: the module is
# named `20_landing`, which is not an identifier, so `import` cannot reach it. Loading it also loads
# `19_pages` behind it, which is where `SITE` comes from -- one string for the site's absolute URL,
# shared by the canonical tags, the sitemap, and the host line at the bottom of every card.
spec = importlib.util.spec_from_file_location("b20", HERE / "20_landing.py")
b20 = importlib.util.module_from_spec(spec)
sys.modules["b20"] = b20
spec.loader.exec_module(b20)

SITE = b20.SITE
DATA = ROOT / "docs" / "data.json"

# What every scraper crops to. 1200x630 is 1.91:1, which is Facebook's and Slack's stated minimum for
# a large card and what X reads as `summary_large_image`; anything squarer gets letterboxed by one of
# them. Asserted against the render rather than trusted, in `dimensions()`.
W, H = 1200, 630

TOP = 3            # names on the card, per the ticket
NAME_CAP = 26      # characters, before the CSS has to ellipsize -- see `card_html`

# Bumping this changes every signature and so re-renders all 27 cards. That is ~540 KB of history, so
# it is a deliberate act: any edit to `card_html` that changes the pixels of an *existing* card needs
# it, and nothing else does. Adding the root card did not: a facet record grew no keys, so its signature
# did not move, so its committed pixels were never questioned.
#
# Colour is the one class of pixel change this no longer has to remember, because `PALETTE` below is
# hashed beside it. What is left for `TEMPLATE` is what the hash cannot see: a layout, size or type edit
# in the stylesheet, a font Chromium resolves differently, a rasterizer worth forcing through.
TEMPLATE = 2

# Every colour on a card, hoisted out of `card_html`'s stylesheet so that the signature can cover it.
#
# It could not before. `signature()` hashed `TEMPLATE` and the record -- the record being what a card
# *says* -- while each colour was a literal in the CSS below, which put the card's appearance outside
# the cache key that decides whether to re-render it. So a re-theme moved no signature, `main()` skipped
# all 27, the stage reported success, and the committed PNGs went on serving the previous palette while
# every other surface on the site moved. Nothing in a browser would show it: the pages re-theme from
# their own CSS, and the only symptom is a link pasted into Slack, Discord, iMessage or X. `TEMPLATE`
# was the answer to this and it was a manual one -- forget the bump and nothing fails.
#
# This repository has already paid for one cache key that did not cover its own input. `docs/sw.js`'s
# `VERSION` hashes the files the worker precaches, so rewriting `docs/index.html` without re-running
# `24_pwa.py` left the worker byte-identical and returning readers pinned to the old shell with no
# self-healing path, because the file that would have triggered the update was the one that had not
# changed (fixed in `87250a1`). Same shape here, with a slower fuse and a wider blast radius, because
# this artefact is what a stranger sees first.
#
# Roles and values come from `19_pages.py`'s dark custom properties. The body and chips use the page's
# secondary ink while the heading and count lift to its white primary ink at thumbnail size.
PALETTE = {
    "surface": "#000000",   # the card, and the backdrop Chromium paints under it -- see `shoot()`
    "band":    "#14141b",   # chip fill
    "ink":     "#c7c9d2",   # body text, and the chips'
    "ink2":    "#9598a4",   # the count line
    "muted":   "#9598a4",   # blurb, label, host line
    "grid":    "#262630",   # chip border
    "bar":     "#ce54af",   # the accent: the frame's top border, and the kicker
    "warn":    "#fff",      # the count itself
    "head":    "#fff",      # the heading -- the only colour here that is not a page variable
}

# The root card's file name, and the one string `19_pages.py` has to agree with -- it is what the root
# page's `og:image` points at. Spelled here rather than there because this is the stage that writes it;
# there is no import between the two that could carry it -- the same seam `20_landing.OG` sits on.
ROOT_CARD = "root.png"

CHROME = chrome.PATH


# ------------------------------------------------------------------ what each card says
def about(n: int) -> str:
    """The count, floored to ten and marked as floored.

    Under twenty there is nothing to floor to -- an 11-project facet would read "10+", which is true
    but throws away the only interesting thing about a small facet, that it is small. Above it the
    imprecision is the point: see the module docstring on why a card must not carry a number that
    moves.
    """
    return f"{n:,}" if n < 20 else f"{n // 10 * 10:,}+"


def clip_name(name: str) -> str:
    """Hard-cap a project name.

    The CSS ellipsizes as well, and it has to -- glyph widths differ between this machine's Segoe UI
    and the runner's DejaVu Sans, so no character count is a width. This cap is for the outliers that
    would otherwise squeeze the other two chips to nothing: "OmniRoute: Multi-Provider LLM Gateway" is
    37 characters, and three of those on one row is more than the card is wide.
    """
    return name if len(name) <= NAME_CAP else name[:NAME_CAP - 1].rstrip(" ,:;-/") + "…"


def signature(rec: dict) -> str:
    """Everything that decides a card's pixels except the rasterizer, in sixteen hex characters.

    The record is what the card says, `PALETTE` is what it looks like, and `TEMPLATE` is the manual bump
    for the rest. `main()` re-renders a card when this moves and skips it when it does not, so anything
    left out of here is something that can change while the committed PNG does not follow it -- which is
    exactly what the palette used to be. A cache key has to cover its own input.

    `sort_keys` is what makes the hashed thing `PALETTE`'s role-to-colour mapping rather than its
    declaration order: reorder the block and no card re-renders, change which colour `bar` means and all
    27 do. Renaming a role does re-render, and that is the right way round -- a rename is cheap to avoid
    and a missed re-theme is not.

    Nothing here is read off disk, deliberately. This repository is `core.autocrlf=true` with no
    `.gitattributes`, so the working tree is CRLF on Windows and LF on the runner: any hash taken over
    file bytes -- `card_html`'s source text, say, which would catch layout too -- would come out
    different on the two platforms, and they would re-render each other's cards for ever. Hashing
    the palette as data is platform-independent by construction. That trap has fired here once already,
    on `24_pwa.py`'s service-worker `VERSION` (`87250a1`).
    """
    return hashlib.sha1(
        json.dumps([TEMPLATE, PALETTE, rec], sort_keys=True, ensure_ascii=False).encode()
    ).hexdigest()[:16]


def cards(pages: list, data: dict) -> list[dict]:
    """The 27 views with a card of their own -- the unfiltered root, then the 26 single-axis facets.

    One filter, no filter, both filters: the three cases `20_landing.plan()` produces and this is
    where they are told apart. Two of them get an image. The root gets one because it is the URL that
    is shared; a crossing does not, because its topic's card already says everything a per-cell image
    could without contradicting the crossing page's own title.

    Returned as plain dicts rather than as the `Page` objects they came from, because this is also
    what gets hashed into a signature and written to `cards.json`: if the record and the render take
    their strings from two different places, a card can drift from its own ledger entry and the skip
    below would then keep serving the stale one for ever.
    """
    # The no-filter view. `plan()` does not emit a `Page` for it -- it has no facet to hang one on --
    # so its record is assembled here, out of the same `data` those pages were grouped from, and then
    # goes through `card_html` exactly as the 26 do. Every string below lands in a slot a facet card
    # already has: heading, count line, one-line blurb, labelled chip row, host line.
    #
    # The 14 topic pages partition the dataset -- `plan()` files every row under its single `cat` --
    # so concatenating their rows is the whole atlas, and re-ranking that by the key `plan.rank` uses
    # is the root view's own top three. Taken this way rather than from `data["rows"]` so that the
    # names on this card come out of the same already-resolved dicts the facet cards read.
    everything = [r for p in pages if p.cat and not p.tgt for r in p.rows]
    everything.sort(key=lambda r: (-(r["stars"] or 0), r["name"].lower()))
    # The lists that actually contributed a surviving row, which is the honest number for a card that
    # claims them: a source parsed but wholly deduplicated away is not a list this index is built on.
    # `listed_by` is a comma-joined label string per row -- `22_detail.py` splits it the same way.
    lists = {n.strip() for r in everything for n in r["listed_by"].split(",") if n.strip()}
    out = [{
        "file": ROOT_CARD,
        # What the atlas *is*, in the slot a facet spends on its own name. Not "Awesome Agentic Atlas":
        # the kicker above it already says that, and a card whose headline repeats its own kicker has
        # spent its largest type telling the reader nothing.
        "title": "Every agentic AI tool, one index",
        "count": about(len(everything)),
        # Two more counts in the slot a facet spends on its cross-axis, and both are printed exactly
        # rather than through `about()` -- 11 and 14 are below its flooring threshold anyway, and they
        # are the two numbers the generic repository card structurally cannot carry, because it is
        # rendered from a name and a description and knows nothing about the dataset.
        "scope": f"{len(lists)} source lists · {len(data['cats'])} topics",
        # Written here rather than clipped out of prose elsewhere, because there is no root blurb in
        # `data.json` to clip: the site's own `<meta name=description>` is the nearest thing and it
        # leads with a count this line would then print twice.
        "blurb": "Merged, deduplicated, and filterable by topic, harness and operating system.",
        "names": [clip_name(r["name"]) for r in
                  sorted(everything[:TOP], key=lambda r: r["name"].lower())],
        # The one string on any card here that moves with the data rather than with the taxonomy, and
        # the module docstring argues the churn. It goes on the host line because that is the card's
        # smallest, quietest type: a date is metadata, and giving it the count line's weight would say
        # the freshness matters more than the size, which is backwards for a link somebody is deciding
        # whether to click. `data["snapshot"]`, not today's date -- the page prints the same field, and
        # a card claiming a build date newer than the data it describes is the one lie available here.
        "note": f" · snapshot {data['snapshot']}",
    }]
    for p in pages:
        # Both set is a crossing, neither is impossible; either way there is no card of its own.
        if bool(p.cat) == bool(p.tgt):
            continue
        kind = "topic" if p.cat else "target"
        facet = p.cat or p.tgt
        out.append({
            "file": f"{kind}-{facet['slug']}.png",
            "title": p.heading,
            "count": about(len(p.rows)),
            # The axis this card does *not* fix. It is what makes the card safe to reuse on the 130
            # crossing pages: "every harness" contradicts nothing a crossing page says about itself.
            "scope": "every harness" if p.cat else "every topic",
            # The taxonomy's own blurb, which is already written prose and is the one thing on the
            # card that costs nothing to put there: it is hand-edited text in `data.json`, so it moves
            # when somebody rewrites a topic description and on no other day. 90 characters because
            # the card gives it exactly one line -- see `card_html`.
            "blurb": b20.clip(facet["blurb"], 90),
            "names": [clip_name(r["name"]) for r in
                      sorted(p.rows[:TOP], key=lambda r: r["name"].lower())],
        })
    # Signed in one pass at the end rather than inside the loop, so the root record is hashed by the
    # same call as the other 26. Each record is hashed before it has a `"sig"` key, which is what it was
    # before and is what keeps the 26 facet signatures -- and so their committed pixels -- untouched by
    # this function growing a 27th entry.
    for rec in out:
        rec["sig"] = signature(rec)
    return out


# ------------------------------------------------------------------ the card itself
def card_html(rec: dict, host: str) -> str:
    """One card as a 1200x630 document, for Chromium to rasterize.

    HTML rather than SVG, and it is the layout that decides it: an `<svg>` has no line breaking and no
    ellipsis, so every string on the card would need to be measured in Python against a font this
    process cannot see. CSS measures it in the renderer that is about to draw it -- `-webkit-line-clamp`
    on the heading and `flex-shrink` with `text-overflow` on the chips mean a facet name that takes
    two lines in DejaVu Sans where it took one in Segoe UI still fits inside the frame rather than
    hanging out of it. Nothing here is written to `docs/`; the document is scaffolding in a temporary
    directory and the PNG is the output.

    The colours are `19_pages.py`'s dark palette, character for character, on the same argument
    `20_landing.py` makes for copying the two custom-property blocks: a card is the first thing anyone
    sees of this site and it has to be the same cyan and the same near-black as the page behind it. They
    live in `PALETTE` rather than in the stylesheet below so that `signature()` can hash them, which is
    what makes a re-theme re-render the cards instead of silently leaving them on the old palette.

    One record shape, 27 cards. The only slot whose *content* differs between the root card and a facet
    card is the host line's suffix, and it is optional rather than required of every record for a reason
    measured in committed bytes: a facet record has no `"note"` key, so its signature is what it was
    before this document grew the ability to carry one, so `main()` skips it and no render happens at
    all. Requiring the key -- even with an empty value -- would have rewritten all 26 PNGs to produce
    the same pixels.
    """
    esc = b20.esc
    # Unpacked into locals so that the stylesheet below still reads as a stylesheet rather than as nine
    # dictionary lookups. Named for the `19_pages.py` custom property each one came from.
    surface, band, grid = PALETTE["surface"], PALETTE["band"], PALETTE["grid"]
    ink, ink2, muted = PALETTE["ink"], PALETTE["ink2"], PALETTE["muted"]
    bar, warn, head = PALETTE["bar"], PALETTE["warn"], PALETTE["head"]
    chips = "".join(f'<span class=chip>{esc(n)}</span>' for n in rec["names"])
    # `"note" in rec` rather than `rec.get("note", "")`, and the difference is not style: a facet record
    # that carried the key with an empty value would hash differently and re-render all 26 committed
    # PNGs to produce the same pixels. Absence is the default, so absence is what the facet records say.
    note = esc(rec["note"]) if "note" in rec else ""
    return f"""<!doctype html>
<html lang=en><head><meta charset=utf-8><style>
/* The frame is fixed and clipped. `overflow:hidden` is the guarantee that matters: Chromium's
   --screenshot captures the window, so content that overflowed would not be cropped by the card, it
   would push the layout and silently shift everything above it. */
html,body{{margin:0;padding:0;width:{W}px;height:{H}px;overflow:hidden}}
body{{background:{surface};color:{ink};
  font:400 16px/1.4 "Segoe UI","DejaVu Sans",system-ui,-apple-system,Helvetica,Arial,sans-serif}}
/* The accent is a border on the frame rather than a positioned bar, so `box-sizing` keeps the total
   at exactly {H}px however thick it gets. */
.card{{box-sizing:border-box;width:{W}px;height:{H}px;padding:54px 72px 44px;
  border-top:14px solid {bar};display:flex;flex-direction:column}}
.kick{{font-size:25px;font-weight:600;letter-spacing:.16em;text-transform:uppercase;color:{bar}}}
/* Two lines, then ellipsis. Three would collide with the count line, and the longest facet name here
   ("Sandbox, Security & Governance") is already two at this size in a wide font.

   This is the only element on the card whose height is not fixed, which is deliberate: every line
   height here is set in CSS rather than left to the font, so the frame's total is the same in Segoe
   UI and in the runner's DejaVu Sans, and the one variable left -- one heading line or two -- is
   absorbed by the `margin-top:auto` below. Measured through --dump-dom, the two-line worst case
   comes to 597 of the {H}px available, so the tightest card still has 33px of air in it. */
h1{{margin:24px 0 0;font-size:76px;line-height:1.05;letter-spacing:-.02em;font-weight:700;color:{head};
  display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}}
.count{{margin-top:18px;font-size:33px;color:{ink2}}}
.count b{{color:{warn};font-weight:700}}
/* One line, never two. Wrapping is what would make the card's height depend on glyph widths, so the
   blurb is clipped to 90 characters in Python for sense and ellipsized here for width -- whichever
   runs out first, the line count is one. */
.blurb{{margin-top:14px;font-size:26px;color:{muted};white-space:nowrap;overflow:hidden;
  text-overflow:ellipsis}}
/* Pushed to the floor, so a one-line heading and a two-line heading both leave the names where the
   eye already found them on the last card it saw. */
.names{{margin-top:auto}}
.lbl{{font-size:20px;font-weight:600;letter-spacing:.14em;text-transform:uppercase;color:{muted}}}
.row{{display:flex;gap:14px;margin-top:14px}}
/* `min-width:0` is what makes the ellipsis reachable -- a flex item's floor is its content width
   otherwise, so the three chips would overflow the row instead of shrinking inside it. */
.chip{{flex:0 1 auto;min-width:0;background:{band};border:1px solid {grid};border-radius:999px;
  padding:11px 21px;font-size:25px;color:{ink};white-space:nowrap;overflow:hidden;
  text-overflow:ellipsis}}
.host{{margin-top:20px;font-size:22px;color:{muted}}}
</style></head><body><div class=card>
<div class=kick>Awesome Agentic Atlas</div>
<h1>{esc(rec["title"])}</h1>
<div class=count><b>{esc(rec["count"])}</b> projects &middot; {esc(rec["scope"])}</div>
<div class=blurb>{esc(rec["blurb"])}</div>
<div class=names>
  <!-- "A-Z" is not decoration. The three names are *selected* by star count and then sorted
       alphabetically, so that two projects swapping rank does not rewrite the PNG -- see `cards()`.
       Under a bare "Most starred" a row of three pills reads as a ranking, and it is not one, so the
       card would be claiming an order its own churn budget deliberately gave up.

       True of the root card without a word changed, which is why it takes this label rather than one
       of its own: "the three most starred" of the no-filter view is the three most starred projects in
       the atlas, and the same alphabetical sort keeps the same churn promise over them. -->
  <div class=lbl>Most starred &middot; A&ndash;Z</div>
  <div class=row>{chips}</div>
</div>
<div class=host>{esc(host)}{note}</div>
</div></body></html>
"""


def shoot(rec: dict, host: str) -> bytes | None:
    """One card, one Chromium subprocess. None if anything about it fails.

    Deliberately not a browser held open across 26 renders: a hung page then takes the whole stage
    with it, and this is the pattern both shot stages already use for exactly that reason.

    --force-device-scale-factor=1 pins the output at {W}x{H} rather than whatever DPI the host thinks
    it has, and --font-render-hinting=none takes the hinter out of the picture, which is the one
    rendering variable that changes with the runner's freetype rather than with our content -- and a
    render that changed is 24 KB of history whether or not anything on the card did.

    --default-background-color is the one colour that is not in the document, so it is taken from
    `PALETTE` rather than spelled again: it is what Chromium paints before the page's own background
    lands, and a re-theme that changed the surface everywhere except in this argument would leave the
    card's own backdrop behind -- outside the stylesheet, where nobody rereading the CSS would find it.
    The flag wants bare RRGGBBAA, hence the `#` coming off and the opaque `ff` going on.
    """
    if not CHROME:
        return None
    with tempfile.TemporaryDirectory() as td:
        page = Path(td) / "card.html"
        page.write_text(card_html(rec, host), encoding="utf-8")
        out = Path(td) / "card.png"
        cmd = [str(CHROME), "--headless", "--disable-gpu", "--hide-scrollbars", "--no-sandbox",
               "--disable-dev-shm-usage", f"--screenshot={out}", f"--window-size={W},{H}",
               "--force-device-scale-factor=1", "--font-render-hinting=none",
               f"--default-background-color={PALETTE['surface'].lstrip('#')}ff",
               "--virtual-time-budget=1500",
               page.as_uri()]
        try:
            subprocess.run(cmd, capture_output=True, timeout=60)
        except Exception:
            return None
        if not out.exists() or out.stat().st_size < 2000:
            return None
        return out.read_bytes()


# ------------------------------------------------------------------ PNG: read, index, write
def chunks(png: bytes):
    """Walk a PNG's chunks. Stops at the first malformed length rather than raising."""
    pos = 8
    while pos + 8 <= len(png):
        length, typ = struct.unpack(">I4s", png[pos:pos + 8])
        if pos + 12 + length > len(png):
            return
        yield typ, png[pos + 8:pos + 8 + length]
        pos += 12 + length


def dimensions(png: bytes) -> tuple[int, int] | None:
    """(width, height) from IHDR, or None if this is not a PNG. The build's only proof of size."""
    if not png.startswith(b"\x89PNG\r\n\x1a\n"):
        return None
    for typ, body in chunks(png):
        if typ == b"IHDR":
            return struct.unpack(">II", body[:8])
    return None


def unfilter(raw: bytes, w: int, h: int, bpp: int) -> list[bytearray] | None:
    """Reverse the five PNG line filters. `None` on anything unexpected, never an exception.

    Written out rather than delegated because there is nothing to delegate to in the standard library
    -- and it is worth having: Chromium's own output uses Up on three quarters of the lines and Paeth
    on most of the rest, so the cheap path of "assume filter 0" would decode noise.
    """
    stride = w * bpp
    if len(raw) != h * (stride + 1):
        return None
    rows, prev, pos = [], bytearray(stride), 0
    for _ in range(h):
        ft = raw[pos]
        pos += 1
        line = bytearray(raw[pos:pos + stride])
        pos += stride
        if ft == 1:
            for i in range(bpp, stride):
                line[i] = (line[i] + line[i - bpp]) & 0xFF
        elif ft == 2:
            for i in range(stride):
                line[i] = (line[i] + prev[i]) & 0xFF
        elif ft == 3:
            for i in range(stride):
                a = line[i - bpp] if i >= bpp else 0
                line[i] = (line[i] + ((a + prev[i]) >> 1)) & 0xFF
        elif ft == 4:
            for i in range(stride):
                a = line[i - bpp] if i >= bpp else 0
                b = prev[i]
                c = prev[i - bpp] if i >= bpp else 0
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                line[i] = (line[i] + (a if pa <= pb and pa <= pc else b if pb <= pc else c)) & 0xFF
        elif ft != 0:
            return None
        rows.append(line)
        prev = line
    return rows


def indexed(png: bytes) -> bytes:
    """Re-encode as an 8-bit palette PNG, or hand back the original if that cannot be done safely.

    The palette is the 256 most frequent colours, ordered by frequency and then by value so the same
    render always produces the same file -- byte-identical output for unchanged content is the whole
    basis of the skip in `main()`, and a palette that depended on dictionary order would quietly
    destroy it. Everything rarer is snapped to its nearest entry by squared distance in RGB, memoized
    per colour: the alternative is 756,000 nearest-neighbour searches instead of ~1,700.

    Filter 0 on the way out, measured rather than assumed -- on indexed data an index is a name, not a
    magnitude, so Up and Sub both encode differences between unrelated palette slots and both come out
    larger than storing the indices raw (30.7 KB and 26.6 KB against 23.1 KB on the first card built).
    """
    head = None
    idat = bytearray()
    for typ, body in chunks(png):
        if typ == b"IHDR":
            head = struct.unpack(">IIBBBBB", body)
        elif typ == b"IDAT":
            idat += body
    if head is None:
        return png
    w, h, depth, colour, comp, filt, interlace = head
    # 8-bit truecolour with or without alpha, not interlaced, is what Chromium writes. Anything else
    # is a Chromium that changed its encoder, and the honest response to that is to ship its bytes.
    if (depth, comp, filt, interlace) != (8, 0, 0, 0) or colour not in (2, 6):
        return png
    try:
        raw = zlib.decompress(bytes(idat))
    except zlib.error:
        return png
    bpp = 3 if colour == 2 else 4
    rows = unfilter(raw, w, h, bpp)
    if rows is None:
        return png

    stride = w * bpp
    counts: dict[bytes, int] = {}
    for line in rows:
        for i in range(0, stride, bpp):
            px = bytes(line[i:i + 3])
            counts[px] = counts.get(px, 0) + 1
    palette = [c for c, _ in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))][:256]
    lut = {c: bytes([i]) for i, c in enumerate(palette)}
    rgb = [(c[0], c[1], c[2]) for c in palette]
    for c in counts:
        if c in lut:
            continue
        r, g, b = c[0], c[1], c[2]
        best, dist = 0, 1 << 30
        for i, (pr, pg, pb) in enumerate(rgb):
            d = (r - pr) ** 2 + (g - pg) ** 2 + (b - pb) ** 2
            if d < dist:
                best, dist = i, d
        lut[c] = bytes([best])

    # Identical scanlines are most of a card -- 355 of 630 on the first one built, all background --
    # and re-indexing each of them costs 1,200 dictionary lookups it has already done.
    body, seen = bytearray(), {}
    for line in rows:
        key = bytes(line)
        enc = seen.get(key)
        if enc is None:
            enc = b"\x00" + b"".join(lut[bytes(line[i:i + 3])] for i in range(0, stride, bpp))
            seen[key] = enc
        body += enc

    def chunk(typ: bytes, data: bytes) -> bytes:
        return (struct.pack(">I", len(data)) + typ + data
                + struct.pack(">I", zlib.crc32(typ + data) & 0xFFFFFFFF))

    small = (b"\x89PNG\r\n\x1a\n"
             + chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 3, 0, 0, 0))
             + chunk(b"PLTE", b"".join(palette))
             + chunk(b"IDAT", zlib.compress(bytes(body), 9))
             + chunk(b"IEND", b""))
    # A card is flat fills and text, so this always wins by a factor of two or more; the guard is for
    # the day somebody puts a photograph on one, where 8-bit RGB is the right encoding and this is not.
    return small if len(small) < len(png) else png


# ------------------------------------------------------------------ writing
def prune(keep: set[str], out: Path) -> list[str]:
    """Delete cards for views that no longer exist.

    Same argument as `20_landing.py`'s prune: a renamed topic otherwise leaves a card that is still
    served and still named after something that is gone. Only `*.png` under `out` is touched.
    """
    gone = []
    for path in sorted(out.glob("*.png")):
        if path.name not in keep:
            path.unlink()
            gone.append(path.name)
    return gone


def main(out: Path = OUT) -> None:
    """Render into `out`, which is `docs/og/` unless `--out` said otherwise.

    The override exists because the default is a directory GitHub Pages serves verbatim out of this
    branch, so "let me see what this design change looks like" and "publish 27 new PNGs and rewrite the
    ledger" were the same command. Seed the temporary directory with a copy of `docs/og/` and only the
    card being worked on re-renders; leave it empty and all 27 do.
    """
    data = json.loads(DATA.read_text(encoding="utf-8"))
    recs = cards(b20.plan(data), data)
    host = SITE.split("//", 1)[-1].rstrip("/")

    out.mkdir(parents=True, exist_ok=True)
    ledger = out / "cards.json"
    old = {}
    if ledger.exists():
        try:
            old = json.loads(ledger.read_text(encoding="utf-8")).get("cards", {})
        except json.JSONDecodeError:
            old = {}          # a truncated ledger re-renders everything, which is only ever expensive

    kept, built, failed = [], [], []
    entries: dict[str, dict] = {}
    for rec in recs:
        name, path, was = rec["file"], out / rec["file"], old.get(rec["file"], {})
        said = {k: v for k, v in rec.items() if k != "file"}
        if path.exists() and was.get("sig") == rec["sig"]:
            kept.append(name)
            entries[name] = {**said, "bytes": path.stat().st_size}
            continue
        png = shoot(rec, host)
        size = dimensions(png) if png else None
        if size != (W, H):
            # No browser, a render that produced nothing, or -- never yet seen, and worth refusing to
            # publish if it happens -- a canvas that is not 1.91:1, which every scraper crops
            # differently and which is the failure this whole stage exists to fix.
            failed.append(name if png is None else
                          f"{name} ({size[0]}x{size[1]} not {W}x{H})" if size else
                          f"{name} (not a PNG)")
            # Whatever is committed beats nothing, so it stays -- and so does its ledger entry.
            # Recording this run's signature against last run's pixels is how a card sticks stale for
            # ever: the next run would match the signature and skip the render that is owed.
            if path.exists() and was:
                entries[name] = was
            continue
        png = indexed(png)
        path.write_bytes(png)
        built.append(name)
        entries[name] = {**said, "bytes": len(png)}

    # `palette` is recorded beside `template` for the same reason the strings are recorded beside the
    # signature: so that "are these cards on the current palette?" is answered by reading the committed
    # ledger against `PALETTE` rather than by launching a browser and comparing 27 PNGs. It is the
    # other half of the input the signature is taken over, and a hash alone would say two sets differ
    # without saying which colour moved.
    ledger.write_text(json.dumps({"template": TEMPLATE, "palette": PALETTE, "size": [W, H],
                                  "cards": entries}, indent=1, ensure_ascii=False) + "\n",
                      encoding="utf-8")
    # Keyed on the views that exist, not on the entries written: a card whose render failed keeps
    # its file, and a file with no entry is a card from an older run that this one could not vouch
    # for. Neither is stale, and deleting either would take the page's `og:image` down with it.
    gone = prune({r["file"] for r in recs}, out)
    total = sum(e.get("bytes", 0) for e in entries.values())

    kb = b20.kb
    print(f"{len(recs)} cards · {sum(1 for r in recs if r['file'] == ROOT_CARD)} root · "
          f"{sum(1 for r in recs if r['file'].startswith('topic-'))} topic · "
          f"{sum(1 for r in recs if r['file'].startswith('target-'))} target · {W}x{H} · {kb(total)}")
    print(f"{len(built)} rendered, {len(kept)} unchanged and left alone"
          + (f", {len(failed)} owed a render this run could not do" if failed else ""))
    if built:
        print("  built: " + ", ".join(built[:6]) + (" …" if len(built) > 6 else ""))
    if failed:
        print(f"  not rendered: {', '.join(failed[:6])}" + (" …" if len(failed) > 6 else ""))
    if gone:
        print(f"  {len(gone)} stale card(s) removed: {', '.join(gone[:6])}")
    # Reported from what this run actually used rather than from `chrome.describe()`, so the line can
    # never claim a browser the stage did not have.
    print(f"chrome: {CHROME if CHROME else 'none found -- cards left exactly as committed'}")
    if out != OUT:
        print(f"wrote to {out} -- docs/og/ untouched")


if __name__ == "__main__":
    # Hand-rolled because no stage in this pipeline reaches for `argparse` and one optional path is not
    # where that starts. Stricter than its neighbours in one respect, deliberately: an unrecognised
    # argument is refused rather than ignored, because the failure mode of a silently dropped `--out`
    # is 27 PNGs written into the directory Pages serves.
    argv = sys.argv[1:]
    if not argv:
        main()
    elif len(argv) == 2 and argv[0] == "--out":
        main(Path(argv[1]).resolve())
    else:
        sys.exit(f"usage: {Path(__file__).name} [--out DIR]")
