"""Render one Open Graph card per facet, so a shared link previews as the view it actually is.

`19_pages.py` and `20_landing.py` both point `og:image` at `opengraph.githubassets.com/1/<repo>`,
which is the same generic repository card on all 157 URLs this site publishes. The whole pitch is that
"the best Claude Code observability tool" is a *link*; in Slack, Discord, X and iMessage that link
currently looks identical to a link to the repository's front page -- which is the one surface where
the crossing this site exists to show does not exist at all.

  docs/og/topic-<slug>.png     14, one per topic
  docs/og/target-<slug>.png    12, one per target
  docs/og/cards.json           what each card says, and the signature that decides re-rendering

  python scripts/23_og.py

After `20_landing.py`, and it reads the dataset through that stage's own `plan()` rather than
regrouping 1,294 rows a second time: a card and the page it belongs to cannot then disagree about a
count or about which three projects are the biggest. Nothing else is imported from it, so the two
stages stay independently runnable.

Six decisions, in the order they cost the most.

26 cards, not 156. The 130 crossings reuse their topic's card. What a per-crossing image would add
over its topic's is that cell's own count and top three -- and `20_landing.py` already writes both
into the crossing's `<title>` and `<meta name=description>`, which is the text every one of those
scrapers renders beside the image. The bill for the duplicate is six times the bytes in a format that
cannot delta-compress: every generated byte is committed, because Pages serves this branch's `docs/`
folder. So the card says "every harness" or "every topic" out loud, and a topic card sitting beside a
crossing page's own "12 projects that plug into Claude Code" cannot be read as a claim about that
cell. To reverse the decision, drop the `bool(p.cat) == bool(p.tgt)` skip in `cards()` and give the
crossings a `topic-<a>--target-<b>.png`; nothing else in this stage counts on there being 26.

Nothing that moves daily goes on a card. These pages lead with combined stars and a snapshot date and
neither is here, because a PNG whose pixels moved is a whole new object in the pack for ever -- there
is no such thing as a small edit to one. The count is floored to a multiple of ten and suffixed `+`
for the same reason: "470+ projects" stays true about ten times longer than "479 projects" does, and a
social card is not where anybody reads a precise number. The three names are the top three by stars,
printed in alphabetical order under a label rather than numbered, because the *set* of the three
biggest projects in a facet holds for months while the order of the second and third flips whenever
they trade a few hundred stars -- and a numbered list would turn every one of those flips into a
rewrite of the whole file.

A card is re-rendered only when what it says changes. `docs/og/cards.json` holds the exact strings
that went onto each card plus a signature over them and `TEMPLATE`, so an unchanged facet costs no
browser launch and, more to the point, no bytes. That is what stops a Chromium update on the runner
from rewriting the entire set: `weekly.yml` does `pip install --upgrade playwright` and then
`playwright install chromium`, so the rasterizer moves every few weeks, and text rendered a pixel
differently is 26 new objects. Committed rather than left in `cache/`, which is gitignored and
restored best-effort -- a cache miss there would be indistinguishable from 26 changed cards and would
cost the history ~520 KB to find that out. Bump `TEMPLATE` to force the set through after a design
change.

A missing browser is not an error. Same contract as `15_shots_all.py` and `06_web_shots.py`: one
subprocess per image, `chrome.find()` may return None, and None degrades. It degrades better here
than there, because these cards are committed -- so "no Chromium" means the cards already on disk are
left exactly as they are, which is also what a card whose content did not change gets. The only state
this cannot serve is a facet that has never been rendered, and `20_landing.py` handles that one by
listing `docs/og/` and falling back to the repository card for any page whose file is not there.

Chrome's PNG is re-encoded as an indexed one, with `zlib` and nothing else. A card is flat fills and
antialiased text, so 8-bit RGB spends three bytes on a palette of about 1,900 colours of which 256
cover 99.2% of the pixels: indexing costs ~24 KB where Chrome writes ~60 KB, and the 2.5x applies to
every rewrite for the life of the repository. Lossless when a render has 256 colours or fewer, and
nearest-neighbour among the 256 most frequent otherwise, which on this design is invisible -- every
colour in the image is a point on a blend between one of six inks and one of three backgrounds, so
the nearest palette entry is a neighbour on the same ramp. Anything this cannot parse as an 8-bit
non-interlaced RGB or RGBA PNG is written through unchanged: a smaller card is worth having and a
corrupt one is not.

Dark only. The site ships a light theme and this does not, because a scraper never tells us which one
the reader has and dark is the designed mode -- the mode whose eight neutrals and two accents were
measured. A light card would be a second 26 files that nobody can request.
"""
from __future__ import annotations

import hashlib
import importlib.util
import json
import struct
import subprocess
import sys
import tempfile
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HERE = Path(__file__).resolve().parent
OUT = ROOT / "docs" / "og"

sys.path.insert(0, str(HERE))
import chrome  # noqa: E402

# The dynamic load `20_landing.py` and `19b_refresh.py` both use, for the same reason: the module is
# named `20_landing`, which is not an identifier, so `import` cannot reach it. Loading it also loads
# `19_pages` behind it, which is where `SITE` comes from -- one string for the site's absolute URL,
# shared by the canonical tags, the sitemap, and the host line at the bottom of every card.
spec = importlib.util.spec_from_file_location("b20", HERE / "20_landing.py")
b20 = importlib.util.module_from_spec(spec)
sys.modules["b20"] = b20
spec.loader.exec_module(b20)

SITE = b20.SITE
DATA = ROOT / "docs" / "data.json"

# What every scraper crops to. 1200x630 is 1.91:1, which is Facebook's and Slack's stated minimum for
# a large card and what X reads as `summary_large_image`; anything squarer gets letterboxed by one of
# them. Asserted against the render rather than trusted, in `dimensions()`.
W, H = 1200, 630

TOP = 3            # names on the card, per the ticket
NAME_CAP = 26      # characters, before the CSS has to ellipsize -- see `card_html`

# Bumping this changes every signature and so re-renders all 26 cards. That is ~520 KB of history, so
# it is a deliberate act: any edit to `card_html` below needs it, and nothing else does.
TEMPLATE = 2

CHROME = chrome.PATH


# ------------------------------------------------------------------ what each card says
def about(n: int) -> str:
    """The count, floored to ten and marked as floored.

    Under twenty there is nothing to floor to -- an 11-project facet would read "10+", which is true
    but throws away the only interesting thing about a small facet, that it is small. Above it the
    imprecision is the point: see the module docstring on why a card must not carry a number that
    moves.
    """
    return f"{n:,}" if n < 20 else f"{n // 10 * 10:,}+"


def clip_name(name: str) -> str:
    """Hard-cap a project name.

    The CSS ellipsizes as well, and it has to -- glyph widths differ between this machine's Segoe UI
    and the runner's DejaVu Sans, so no character count is a width. This cap is for the outliers that
    would otherwise squeeze the other two chips to nothing: "OmniRoute: Multi-Provider LLM Gateway" is
    37 characters, and three of those on one row is more than the card is wide.
    """
    return name if len(name) <= NAME_CAP else name[:NAME_CAP - 1].rstrip(" ,:;-/") + "…"


def cards(pages: list) -> list[dict]:
    """The 26 single-axis views, each with the exact strings that go onto its card.

    Returned as plain dicts rather than as the `Page` objects they came from, because this is also
    what gets hashed into a signature and written to `cards.json`: if the record and the render take
    their strings from two different places, a card can drift from its own ledger entry and the skip
    below would then keep serving the stale one for ever.
    """
    out = []
    for p in pages:
        # Both set is a crossing, neither is impossible; either way there is no card of its own.
        if bool(p.cat) == bool(p.tgt):
            continue
        kind = "topic" if p.cat else "target"
        facet = p.cat or p.tgt
        rec = {
            "file": f"{kind}-{facet['slug']}.png",
            "title": p.heading,
            "count": about(len(p.rows)),
            # The axis this card does *not* fix. It is what makes the card safe to reuse on the 130
            # crossing pages: "every harness" contradicts nothing a crossing page says about itself.
            "scope": "every harness" if p.cat else "every topic",
            # The taxonomy's own blurb, which is already written prose and is the one thing on the
            # card that costs nothing to put there: it is hand-edited text in `data.json`, so it moves
            # when somebody rewrites a topic description and on no other day. 90 characters because
            # the card gives it exactly one line -- see `card_html`.
            "blurb": b20.clip(facet["blurb"], 90),
            "names": [clip_name(r["name"]) for r in
                      sorted(p.rows[:TOP], key=lambda r: r["name"].lower())],
        }
        rec["sig"] = hashlib.sha1(
            json.dumps([TEMPLATE, rec], sort_keys=True, ensure_ascii=False).encode()
        ).hexdigest()[:16]
        out.append(rec)
    return out


# ------------------------------------------------------------------ the card itself
def card_html(rec: dict, host: str) -> str:
    """One card as a 1200x630 document, for Chromium to rasterize.

    HTML rather than SVG, and it is the layout that decides it: an `<svg>` has no line breaking and no
    ellipsis, so every string on the card would need to be measured in Python against a font this
    process cannot see. CSS measures it in the renderer that is about to draw it -- `-webkit-line-clamp`
    on the heading and `flex-shrink` with `text-overflow` on the chips mean a facet name that takes
    two lines in DejaVu Sans where it took one in Segoe UI still fits inside the frame rather than
    hanging out of it. Nothing here is written to `docs/`; the document is scaffolding in a temporary
    directory and the PNG is the output.

    The colours are `19_pages.py`'s dark palette, character for character, on the same argument
    `20_landing.py` makes for copying the two custom-property blocks: a card is the first thing anyone
    sees of this site and it has to be the same cyan and the same near-black as the page behind it.
    """
    esc = b20.esc
    chips = "".join(f'<span class=chip>{esc(n)}</span>' for n in rec["names"])
    return f"""<!doctype html>
<html lang=en><head><meta charset=utf-8><style>
/* The frame is fixed and clipped. `overflow:hidden` is the guarantee that matters: Chromium's
   --screenshot captures the window, so content that overflowed would not be cropped by the card, it
   would push the layout and silently shift everything above it. */
html,body{{margin:0;padding:0;width:{W}px;height:{H}px;overflow:hidden}}
body{{background:#101416;color:#d0d7d8;
  font:400 16px/1.4 "Segoe UI","DejaVu Sans",system-ui,-apple-system,Helvetica,Arial,sans-serif}}
/* The accent is a border on the frame rather than a positioned bar, so `box-sizing` keeps the total
   at exactly {H}px however thick it gets. */
.card{{box-sizing:border-box;width:{W}px;height:{H}px;padding:54px 72px 44px;
  border-top:14px solid #08b0cc;display:flex;flex-direction:column}}
.kick{{font-size:25px;font-weight:600;letter-spacing:.16em;text-transform:uppercase;color:#08b0cc}}
/* Two lines, then ellipsis. Three would collide with the count line, and the longest facet name here
   ("Sandbox, Security & Governance") is already two at this size in a wide font.

   This is the only element on the card whose height is not fixed, which is deliberate: every line
   height here is set in CSS rather than left to the font, so the frame's total is the same in Segoe
   UI and in the runner's DejaVu Sans, and the one variable left -- one heading line or two -- is
   absorbed by the `margin-top:auto` below. Measured through --dump-dom, the two-line worst case
   comes to 597 of the {H}px available, so the tightest card still has 33px of air in it. */
h1{{margin:24px 0 0;font-size:76px;line-height:1.05;letter-spacing:-.02em;font-weight:700;color:#fff;
  display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}}
.count{{margin-top:18px;font-size:33px;color:#a8b0b2}}
.count b{{color:#feb932;font-weight:700}}
/* One line, never two. Wrapping is what would make the card's height depend on glyph widths, so the
   blurb is clipped to 90 characters in Python for sense and ellipsized here for width -- whichever
   runs out first, the line count is one. */
.blurb{{margin-top:14px;font-size:26px;color:#8c9496;white-space:nowrap;overflow:hidden;
  text-overflow:ellipsis}}
/* Pushed to the floor, so a one-line heading and a two-line heading both leave the names where the
   eye already found them on the last card it saw. */
.names{{margin-top:auto}}
.lbl{{font-size:20px;font-weight:600;letter-spacing:.14em;text-transform:uppercase;color:#8c9496}}
.row{{display:flex;gap:14px;margin-top:14px}}
/* `min-width:0` is what makes the ellipsis reachable -- a flex item's floor is its content width
   otherwise, so the three chips would overflow the row instead of shrinking inside it. */
.chip{{flex:0 1 auto;min-width:0;background:#232d30;border:1px solid #2c383d;border-radius:999px;
  padding:11px 21px;font-size:25px;color:#d0d7d8;white-space:nowrap;overflow:hidden;
  text-overflow:ellipsis}}
.host{{margin-top:20px;font-size:22px;color:#8c9496}}
</style></head><body><div class=card>
<div class=kick>Awesome Agentic Atlas</div>
<h1>{esc(rec["title"])}</h1>
<div class=count><b>{esc(rec["count"])}</b> projects &middot; {esc(rec["scope"])}</div>
<div class=blurb>{esc(rec["blurb"])}</div>
<div class=names>
  <!-- "A-Z" is not decoration. The three names are *selected* by star count and then sorted
       alphabetically, so that two projects swapping rank does not rewrite the PNG -- see `cards()`.
       Under a bare "Most starred" a row of three pills reads as a ranking, and it is not one, so the
       card would be claiming an order its own churn budget deliberately gave up. -->
  <div class=lbl>Most starred &middot; A&ndash;Z</div>
  <div class=row>{chips}</div>
</div>
<div class=host>{esc(host)}</div>
</div></body></html>
"""


def shoot(rec: dict, host: str) -> bytes | None:
    """One card, one Chromium subprocess. None if anything about it fails.

    Deliberately not a browser held open across 26 renders: a hung page then takes the whole stage
    with it, and this is the pattern both shot stages already use for exactly that reason.

    --force-device-scale-factor=1 pins the output at {W}x{H} rather than whatever DPI the host thinks
    it has, and --font-render-hinting=none takes the hinter out of the picture, which is the one
    rendering variable that changes with the runner's freetype rather than with our content -- and a
    render that changed is 24 KB of history whether or not anything on the card did.
    """
    if not CHROME:
        return None
    with tempfile.TemporaryDirectory() as td:
        page = Path(td) / "card.html"
        page.write_text(card_html(rec, host), encoding="utf-8")
        out = Path(td) / "card.png"
        cmd = [str(CHROME), "--headless", "--disable-gpu", "--hide-scrollbars", "--no-sandbox",
               "--disable-dev-shm-usage", f"--screenshot={out}", f"--window-size={W},{H}",
               "--force-device-scale-factor=1", "--font-render-hinting=none",
               "--default-background-color=101416ff", "--virtual-time-budget=1500",
               page.as_uri()]
        try:
            subprocess.run(cmd, capture_output=True, timeout=60)
        except Exception:
            return None
        if not out.exists() or out.stat().st_size < 2000:
            return None
        return out.read_bytes()


# ------------------------------------------------------------------ PNG: read, index, write
def chunks(png: bytes):
    """Walk a PNG's chunks. Stops at the first malformed length rather than raising."""
    pos = 8
    while pos + 8 <= len(png):
        length, typ = struct.unpack(">I4s", png[pos:pos + 8])
        if pos + 12 + length > len(png):
            return
        yield typ, png[pos + 8:pos + 8 + length]
        pos += 12 + length


def dimensions(png: bytes) -> tuple[int, int] | None:
    """(width, height) from IHDR, or None if this is not a PNG. The build's only proof of size."""
    if not png.startswith(b"\x89PNG\r\n\x1a\n"):
        return None
    for typ, body in chunks(png):
        if typ == b"IHDR":
            return struct.unpack(">II", body[:8])
    return None


def unfilter(raw: bytes, w: int, h: int, bpp: int) -> list[bytearray] | None:
    """Reverse the five PNG line filters. `None` on anything unexpected, never an exception.

    Written out rather than delegated because there is nothing to delegate to in the standard library
    -- and it is worth having: Chromium's own output uses Up on three quarters of the lines and Paeth
    on most of the rest, so the cheap path of "assume filter 0" would decode noise.
    """
    stride = w * bpp
    if len(raw) != h * (stride + 1):
        return None
    rows, prev, pos = [], bytearray(stride), 0
    for _ in range(h):
        ft = raw[pos]
        pos += 1
        line = bytearray(raw[pos:pos + stride])
        pos += stride
        if ft == 1:
            for i in range(bpp, stride):
                line[i] = (line[i] + line[i - bpp]) & 0xFF
        elif ft == 2:
            for i in range(stride):
                line[i] = (line[i] + prev[i]) & 0xFF
        elif ft == 3:
            for i in range(stride):
                a = line[i - bpp] if i >= bpp else 0
                line[i] = (line[i] + ((a + prev[i]) >> 1)) & 0xFF
        elif ft == 4:
            for i in range(stride):
                a = line[i - bpp] if i >= bpp else 0
                b = prev[i]
                c = prev[i - bpp] if i >= bpp else 0
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                line[i] = (line[i] + (a if pa <= pb and pa <= pc else b if pb <= pc else c)) & 0xFF
        elif ft != 0:
            return None
        rows.append(line)
        prev = line
    return rows


def indexed(png: bytes) -> bytes:
    """Re-encode as an 8-bit palette PNG, or hand back the original if that cannot be done safely.

    The palette is the 256 most frequent colours, ordered by frequency and then by value so the same
    render always produces the same file -- byte-identical output for unchanged content is the whole
    basis of the skip in `main()`, and a palette that depended on dictionary order would quietly
    destroy it. Everything rarer is snapped to its nearest entry by squared distance in RGB, memoized
    per colour: the alternative is 756,000 nearest-neighbour searches instead of ~1,700.

    Filter 0 on the way out, measured rather than assumed -- on indexed data an index is a name, not a
    magnitude, so Up and Sub both encode differences between unrelated palette slots and both come out
    larger than storing the indices raw (30.7 KB and 26.6 KB against 23.1 KB on the first card built).
    """
    head = None
    idat = bytearray()
    for typ, body in chunks(png):
        if typ == b"IHDR":
            head = struct.unpack(">IIBBBBB", body)
        elif typ == b"IDAT":
            idat += body
    if head is None:
        return png
    w, h, depth, colour, comp, filt, interlace = head
    # 8-bit truecolour with or without alpha, not interlaced, is what Chromium writes. Anything else
    # is a Chromium that changed its encoder, and the honest response to that is to ship its bytes.
    if (depth, comp, filt, interlace) != (8, 0, 0, 0) or colour not in (2, 6):
        return png
    try:
        raw = zlib.decompress(bytes(idat))
    except zlib.error:
        return png
    bpp = 3 if colour == 2 else 4
    rows = unfilter(raw, w, h, bpp)
    if rows is None:
        return png

    stride = w * bpp
    counts: dict[bytes, int] = {}
    for line in rows:
        for i in range(0, stride, bpp):
            px = bytes(line[i:i + 3])
            counts[px] = counts.get(px, 0) + 1
    palette = [c for c, _ in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))][:256]
    lut = {c: bytes([i]) for i, c in enumerate(palette)}
    rgb = [(c[0], c[1], c[2]) for c in palette]
    for c in counts:
        if c in lut:
            continue
        r, g, b = c[0], c[1], c[2]
        best, dist = 0, 1 << 30
        for i, (pr, pg, pb) in enumerate(rgb):
            d = (r - pr) ** 2 + (g - pg) ** 2 + (b - pb) ** 2
            if d < dist:
                best, dist = i, d
        lut[c] = bytes([best])

    # Identical scanlines are most of a card -- 355 of 630 on the first one built, all background --
    # and re-indexing each of them costs 1,200 dictionary lookups it has already done.
    body, seen = bytearray(), {}
    for line in rows:
        key = bytes(line)
        enc = seen.get(key)
        if enc is None:
            enc = b"\x00" + b"".join(lut[bytes(line[i:i + 3])] for i in range(0, stride, bpp))
            seen[key] = enc
        body += enc

    def chunk(typ: bytes, data: bytes) -> bytes:
        return (struct.pack(">I", len(data)) + typ + data
                + struct.pack(">I", zlib.crc32(typ + data) & 0xFFFFFFFF))

    small = (b"\x89PNG\r\n\x1a\n"
             + chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 3, 0, 0, 0))
             + chunk(b"PLTE", b"".join(palette))
             + chunk(b"IDAT", zlib.compress(bytes(body), 9))
             + chunk(b"IEND", b""))
    # A card is flat fills and text, so this always wins by a factor of two or more; the guard is for
    # the day somebody puts a photograph on one, where 8-bit RGB is the right encoding and this is not.
    return small if len(small) < len(png) else png


# ------------------------------------------------------------------ writing
def prune(keep: set[str]) -> list[str]:
    """Delete cards for facets that no longer exist.

    Same argument as `20_landing.py`'s prune: a renamed topic otherwise leaves a card that is still
    served and still named after something that is gone. Only `*.png` under `docs/og/` is touched.
    """
    gone = []
    for path in sorted(OUT.glob("*.png")):
        if path.name not in keep:
            path.unlink()
            gone.append(path.name)
    return gone


def main() -> None:
    data = json.loads(DATA.read_text(encoding="utf-8"))
    recs = cards(b20.plan(data))
    host = SITE.split("//", 1)[-1].rstrip("/")

    OUT.mkdir(parents=True, exist_ok=True)
    ledger = OUT / "cards.json"
    old = {}
    if ledger.exists():
        try:
            old = json.loads(ledger.read_text(encoding="utf-8")).get("cards", {})
        except json.JSONDecodeError:
            old = {}          # a truncated ledger re-renders everything, which is only ever expensive

    kept, built, failed = [], [], []
    entries: dict[str, dict] = {}
    for rec in recs:
        name, path, was = rec["file"], OUT / rec["file"], old.get(rec["file"], {})
        said = {k: v for k, v in rec.items() if k != "file"}
        if path.exists() and was.get("sig") == rec["sig"]:
            kept.append(name)
            entries[name] = {**said, "bytes": path.stat().st_size}
            continue
        png = shoot(rec, host)
        size = dimensions(png) if png else None
        if size != (W, H):
            # No browser, a render that produced nothing, or -- never yet seen, and worth refusing to
            # publish if it happens -- a canvas that is not 1.91:1, which every scraper crops
            # differently and which is the failure this whole stage exists to fix.
            failed.append(name if png is None else
                          f"{name} ({size[0]}x{size[1]} not {W}x{H})" if size else
                          f"{name} (not a PNG)")
            # Whatever is committed beats nothing, so it stays -- and so does its ledger entry.
            # Recording this run's signature against last run's pixels is how a card sticks stale for
            # ever: the next run would match the signature and skip the render that is owed.
            if path.exists() and was:
                entries[name] = was
            continue
        png = indexed(png)
        path.write_bytes(png)
        built.append(name)
        entries[name] = {**said, "bytes": len(png)}

    ledger.write_text(json.dumps({"template": TEMPLATE, "size": [W, H], "cards": entries},
                                 indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    # Keyed on the facets that exist, not on the entries written: a card whose render failed keeps
    # its file, and a file with no entry is a card from an older run that this one could not vouch
    # for. Neither is stale, and deleting either would take the page's `og:image` down with it.
    gone = prune({r["file"] for r in recs})
    total = sum(e.get("bytes", 0) for e in entries.values())

    kb = b20.kb
    print(f"{len(recs)} cards · {sum(1 for r in recs if r['file'].startswith('topic-'))} topic · "
          f"{sum(1 for r in recs if r['file'].startswith('target-'))} target · {W}x{H} · {kb(total)}")
    print(f"{len(built)} rendered, {len(kept)} unchanged and left alone"
          + (f", {len(failed)} owed a render this run could not do" if failed else ""))
    if built:
        print("  built: " + ", ".join(built[:6]) + (" …" if len(built) > 6 else ""))
    if failed:
        print(f"  not rendered: {', '.join(failed[:6])}" + (" …" if len(failed) > 6 else ""))
    if gone:
        print(f"  {len(gone)} stale card(s) removed: {', '.join(gone[:6])}")
    # Reported from what this run actually used rather than from `chrome.describe()`, so the line can
    # never claim a browser the stage did not have.
    print(f"chrome: {CHROME if CHROME else 'none found -- cards left exactly as committed'}")


if __name__ == "__main__":
    main()
